### PR TITLE
Delegate LOAD/STORE_CAP_PAGE_FAULT exceptions to S-mode.

### PR DESCRIPTION
**Pull request by bsdjhb**

### CODE REVIEW

**Comment by bsdjhb** [comment]
Note that this will die with an assertion failure if the underlying CPU (QEMU or FLUTE, etc.) doesn't support writing these two bits to `medeleg`.  We could perhaps relax the assertion for now to permit those bits to still read back as zero so it's not an immediate flag day of doom (if so I could do that as a second commit so it's easy to revert in the future)

**Comment by jrtc27** [comment]
We have a sentry flag day ongoing already, what's one more thing to add to the pile. Let's just merge this once QEMU support has landed and use it as a forcing function for Flute.

**Comment by jrtc27** [comment]
(QEMU support is also going to be a flag day anyway, since we'll start trapping as soon as we reach anything meaningful in the kernel)

**Comment by bsdjhb** [comment]
Well, if I relaxed this assert, we could push this now, and we could also push CheriBSD now.  CheriBSD will still work if the bits are ignored.  We could then only have the flag day be when QEMU/Flute change.

**Comment by jrtc27** [comment]
Flute will have a bitstream in an hour, just need to upload to AWS (it's passed timing and ready otherwise).

**Pull request merged**
